# range of front sensor
/**:
  ros__parameters:
    device_name: "/dev/ttyUSB0"
    x_range: "20" # input as string, 0.5~20m, steps = 0.5
    y_range: "30" # input as string, 1~30m, steps = 1
    frame: "map"
    x: 2.15 # 1.78+0.37 
    y: 0.0
    z: 0.3